// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	order "ecommerceapi/features/order"

	mock "github.com/stretchr/testify/mock"
)

// OrderData is an autogenerated mock type for the OrderData type
type OrderData struct {
	mock.Mock
}

// Add provides a mock function with given fields: userId, totalPrice
func (_m *OrderData) Add(userId uint, totalPrice float64) (order.Core, string, error) {
	ret := _m.Called(userId, totalPrice)

	var r0 order.Core
	if rf, ok := ret.Get(0).(func(uint, float64) order.Core); ok {
		r0 = rf(userId, totalPrice)
	} else {
		r0 = ret.Get(0).(order.Core)
	}

	var r1 string
	if rf, ok := ret.Get(1).(func(uint, float64) string); ok {
		r1 = rf(userId, totalPrice)
	} else {
		r1 = ret.Get(1).(string)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(uint, float64) error); ok {
		r2 = rf(userId, totalPrice)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// CancelOrder provides a mock function with given fields: orderid
func (_m *OrderData) CancelOrder(orderid uint) error {
	ret := _m.Called(orderid)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(orderid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetOrderHistory provides a mock function with given fields: userId
func (_m *OrderData) GetOrderHistory(userId uint) ([]order.Core, error) {
	ret := _m.Called(userId)

	var r0 []order.Core
	if rf, ok := ret.Get(0).(func(uint) []order.Core); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]order.Core)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSellingHistory provides a mock function with given fields: userId
func (_m *OrderData) GetSellingHistory(userId uint) ([]order.Core, error) {
	ret := _m.Called(userId)

	var r0 []order.Core
	if rf, ok := ret.Get(0).(func(uint) []order.Core); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]order.Core)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NotificationTransactionStatus provides a mock function with given fields: transactionId, transStatus
func (_m *OrderData) NotificationTransactionStatus(transactionId string, transStatus string) error {
	ret := _m.Called(transactionId, transStatus)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(transactionId, transStatus)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewOrderData interface {
	mock.TestingT
	Cleanup(func())
}

// NewOrderData creates a new instance of OrderData. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewOrderData(t mockConstructorTestingTNewOrderData) *OrderData {
	mock := &OrderData{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
